<?php $_items = $this->getCollection(); ?>
<?php if ($_items) : ?>
    <tr>
        <td>
            <table class="items" cellpadding="0" cellspacing="0" border="0">
                <thead>
                <tr>
                    <th class="cell-name">
                        <?php if (count($_items) > 1) : ?>
                            <?php echo $this->__('Items in your order'); ?>
                        <?php else : ?>
                            <?php echo $this->__('Item in your order'); ?>
                        <?php endif; ?>
                    </th>
                    <th class="cell-name align-center">
                        <?php echo $this->__('Qty'); ?>
                    </th>
                    <th class="cell-name align-right">
                        <?php echo $this->__('Price'); ?>
                    </th>
                </tr>
                </thead>
                <?php $i=0; foreach ($_items as $_item) : ?>
                    <?php if($_item->getParentItem()) continue; else $i++; ?>
                    <td>
                        <?php echo $this->escapeHtml($_item->getOrderItem()->getName()); ?>
                    </td>
                    <td>
                        <?php echo $this->escapeHtml($_item->getQty()); ?>
                    </td>
                    <td>
                        <?php echo Mage::helper('core')->currency($_item->getOrderItem()->getPrice(), true, false); ?>
                    </td>
                <?php endforeach; ?>
            </table>
        </td>
    </tr>
<?php endif; ?>
