<?php

/*jimport('joomla.pesapal.oauth');
jimport('joomla.pesapal.xmlhttprequest');*/
require_once (Mage::getBaseDir('base') .DS. 'app'.DS.'code'.DS.'local'.DS.'Pesapal'.DS.'Pesapalexpress'.DS . 'Helper' . DS .'OAuth.php');
//include_once('xmlhttprequest.php');
class JPesapal {
	var $token;
	var $params;
	var $consumer_key; // merchant key
	var $consumer_secret;//  merchant secret
	var $signature_method;//
	var $iframelink;
	var $statusrequest;
	var $detailedstatusrequest;
	public function __construct($key,$secret,$isdemo=false)
	{
		// PHPMailer has an issue using the relative path for it's language files
		
		$this->token = $this->params = NULL;
		

		$this->consumer_key = $key;//'kLHdr+SSwv2EwYvQNiJFAepVc/DAZoQH';//DEMO Merchant
		$this->consumer_secret = $secret;//'CLjAxeY/3hhNbgZybHUV+lSfawE=';//DEMO Key
//		$this->consumer_key = 'lhiP9QWtQQsXWU+G5HdFHEUr41COHMiI';
//		$this->consumer_secret = '5k6xJ7E0G5JFgUowlc+13SFEfkY=';			
		$this->signature_method = new OAuthSignatureMethod_HMAC_SHA1();
		if($isdemo===true){
			$this->iframelink = 'http://demo.pesapal.com/api/PostPesapalDirectOrderMobile';
			$this->statusrequest = 'http://demo.pesapal.com/api/querypaymentstatus';
			$this->detailedstatusrequest = 'http://demo.pesapal.com/API/QueryPaymentDetails';
		}else{
			$this->iframelink = 'https://www.pesapal.com/api/PostPesapalDirectOrderV4';
			$this->statusrequest = 'https://www.pesapal.com/api/querypaymentstatus';
			$this->detailedstatusrequest = 'https://www.pesapal.com/API/QueryPaymentDetails';
		}
		
		

	}
	
	public function loadIframe($details=array()){
		if(count($details)){
			$amount = $details['amount'];
			$desc = $details['desc'];//'Sample Description';
			$code = '';//mpesa/zap code
			$type = 'MERCHANT';
			$payment_method = '';
			$reference = $details['reference'];//'00100-01';//unique order id of the transaction, generated by merchant
			$first_name = $details['first_name'];//'First Name';
			$last_name = $details['last_name'];//'Last Name';
			$email = $details['email'];//'test@gmail.com';
			$phonenumber = '';//leave blank
			$username = $email; //same as email
			$currency=$details['currency'];
			//echo $currency; exit;
			$callback_url = $details['callback_url'];//'http://www.test.com/index.php'; //redirect url, the page that will handle the response from pesapal.
			
			$consumer = new OAuthConsumer($this->consumer_key, $this->consumer_secret);
		

			$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Currency=\"".$currency."\" Description=\"".$desc."\" Code=\"".$code."\" Type=\"".$type."\" PaymentMethod=\"".$payment_method."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" UserName=\"".$username."\" xmlns=\"http://www.pesapal.com\" />";
			$post_xml = htmlentities($post_xml);
			//post transaction to pesapal
			$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $this->token, "GET", $this->iframelink, $this->params);
			$iframe_src->set_parameter("oauth_callback", $callback_url);
			$iframe_src->set_parameter("pesapal_request_data", $post_xml);
			$iframe_src->sign_request($this->signature_method, $consumer, $this->token);
			
			?>
        <iframe src="<?php echo $iframe_src;?>" width="100%" height="700px"  scrolling="no" frameBorder="0">
            <p>Browser unable to load iFrame</p>
        </iframe>
<?php

		}
	}

}