<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Zozothemes\Blog\Block\Sidebar\Recent
 */
?>

<?php
	$_postCollection = $block->getPostCollection();
	
?>
<?php if ($_postCollection->count()) { ?>
<!--<div class="widget block block-recent-posts" data-bind="scope: 'recemt-posts'">
    <div class="block-title">
        <strong><?php //echo __('Recent Posts') ?></strong>
    </div>
    <div class="block-content">-->
    	<?php foreach ($_postCollection as $_post) { ?>
            <div class="blog-item">
                <img src="<?php echo $block->escapeHtml($_post->getFeaturedImage()) ?>" alt="" class="img-responsive"/>
                <div class='post-details'>
                    <div class="post-date"><p><i class="varmo-icon-watch"></i><?php echo date('F j, Y', strtotime($_post->getPublishTime())); ?></p></div>
                    <div class="post-meta">
                        <h3 class="blog-title"><a href="<?php echo $_post->getPostUrl() ?>"><?php echo $block->escapeHtml($_post->getTitle()) ?></a></h3>
                        <p class='blog-description'><?php echo $_post->getContent() ?></p>
                        <a class="read-more" href="<?php echo $_post->getPostUrl() ?>">Read More</a>
                    </div>
                </div>
            </div>
        <?php } ?>
    <!--</div>
</div>-->
<?php } ?>