<?php
$store = Mage::app()->getStore();
$code  = $store->getCode();
$helper = Mage::helper('hybrid');
$custom_block = $helper->getConf('contacts/customblock', $code);


    $_enable = $helper->getConf('contacts/enable', $code);
    if($_enable){
        $_address = $helper->getConf('contacts/address', $code);
        $_zoom = $helper->getConf('contacts/zoom', $code);
        $_center_lat = $helper->getConf('contacts/latitude', $code);
        $_center_lng = $helper->getConf('contacts/longitude', $code);
?>
<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v=3.17"></script>
<script type="text/javascript">
    function initialize() {
        var pos = new google.maps.LatLng(<?php echo $_center_lat; ?>, <?php echo $_center_lng; ?>);
        var mapOptions = {
            center: pos,
            panControl: true,
			scrollwheel: false,
            zoomControl: true,
            mapTypeControl: true,
            scaleControl: true,
            streetViewControl: true,
            overviewMapControl: true,
            zoom: <?php echo $_zoom; ?>
        };
        var map = new google.maps.Map(document.getElementById("store_map"), mapOptions);
        var marker = new google.maps.Marker({
            position: pos,
            map: map,
            title: '<?php echo $_address; ?>'
        });
		var styles = [
					  {
						stylers: [
						  { hue: "#000000" },
						  { saturation: -100 }
						]
					  },{
						featureType: "road",
						elementType: "geometry",
						stylers: [
						  { lightness: 0 },
						  { visibility: "simplified" }
						]
					  },{
						featureType: "road",
						elementType: "labels",
						stylers: [
						  { visibility: "off" }
						]
					  }
					];

		map.setOptions({styles: styles});
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>
<section class="section map-section">
	<div id="store_map" style="min-height: 300px; width: 100%;"></div>
</section>
<?php
    }
?>
<?php if($custom_block): ?>
<section class="section calltoaction-section bg-color">
	<div class="container">
        <div class="row">
            <div class="col-sm-12">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($custom_block)->toHtml(); ?>
            </div>
        </div>
    </div>
</section>
<?php endif; ?>
