<?php 
	$themehelper = $this->helper('hybrid');
	$_themehelper = $themehelper;
	$storeId = Mage::app()->getStore()->getId();
	$nav = 'true';
	$newpagination = 'true';
	$slcount = 4;
	$lazyload = 'true';
	$singleitem = 'true';
	$speed = '300';
	#$w_thumbnail = 135;
	#$h_thumbnail = 135;
	
	$_image_helper = $this->helper('catalog/image');
	$store = Mage::app()->getStore();
	$code  = $store->getCode();
	
	$aspect_ratio = $themehelper->getConf('category_page/aspect_ratio',$code);
	$ratio_width = $themehelper->getConf('category_page/ratio_width',$code);
	$ratio_height = $themehelper->getConf('category_page/ratio_height',$code);
	
	if(!$ratio_width)
		$ratio_width = 300;
	if(!$ratio_height)
		$ratio_height = 400;
		$_helper = $this->helper('catalog/output');
		
	$catId = $this->getData('category_id');
	$_productCollection_model = Mage::getModel('catalog/product')
								->getCollection()
								->joinField('category_id', 'catalog/category_product', 'category_id', 'product_id = entity_id', null, 'left')
								->setStoreId($storeId)
								->addStoreFilter($storeId)
								->addAttributeToSelect('*')
								->addAttributeToFilter('category_id', $catId)
								->addAttributeToFilter('status', array('eq' => 1))
								->addAttributeToFilter('featured', 1)
								->load(); 
	?>
	<?php if(!$_productCollection_model): ?>
		<?php echo "No Featured products available on this category"; ?>
    <?php else: ?>
    <div class="carousel-wrapper">
		<div id="tabbed_categories-<?php echo $catId; ?>" class="owl-carousel <?php if($this->getData('rtl')==='true'):?>owlnav-top-left<?php else:?>owlnav-top-right<?php endif;?> nav-dark">
				<?php $i=0; foreach ($_productCollection_model as $_product): ?> 
                	<?php $product = $_product; ?>

                    <div class="item products-items">
                        
            <div class="product-image-area">  
                      <div class="label-group">
             <?php 
							
                        $sale_label = false;
                        
                        
                        // Get the Special Price
                        $specialprice = $_product->getFinalPrice();
                        $orgprice = $_product->getPrice();
                        // Get the Special Price FROM date
                        $now = date("Y-m-d");
                        $specialPriceFromDate = substr($_product->getSpecialFromDate(),0,10);
                        // Get the Special Price TO date
                        $specialPriceToDate = substr($_product->getSpecialToDate(),0,10);
                        // Get Current date
                        $today =  time();
                     
                        if ($specialprice<$orgprice){
                            $save_percent = 100-round(($specialprice/$orgprice)*100);
                            if ($specialPriceToDate != '' || $specialPriceFromDate != ''){
                            if (($specialPriceToDate != '' && $specialPriceFromDate != '' && $now>=$specialPriceFromDate && $now<=$specialPriceToDate) || ($specialPriceToDate == '' && $now >=$specialPriceFromDate) || ($specialPriceFromDate == '' && $now<=$specialPriceToDate)){
                                if($themehelper->getConf("product_label/sale", $code)){
                                    $sale_label = true;
                    ?>
                                <div class="product-label" style="right: 10px;"><span class="sale-product-icon"><?php if($themehelper->getConf("product_label/sale_label_type", $code)):?><?php echo "-".$save_percent."%"; ?><?php else: ?><?php echo $themehelper->getConf("product_label/sale_label_text", $code);?><?php endif; ?></span></div>
                    <?php       
                                }
                            }
                            }
                        }
                    ?>
                    <?php
                        $now = date("Y-m-d");
                        $newsFrom= substr($_product->getData('news_from_date'),0,10);
                        $newsTo=  substr($_product->getData('news_to_date'),0,10);
                        if ($newsTo != '' || $newsFrom != ''){
                            if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo))
                            {
                                if($themehelper->getConf("product_label/new", $code)){
                        ?> 
                                <div class="product-label" style="right: 10px; <?php echo ($sale_label)?"top: 40px;":""; ?>"><span class="new-product-icon"><?php echo $themehelper->getConf("product_label/new_label_text", $code);?></span></div>
                        <?php 
                                }
                            }
                        }
                    ?>  
				</div>   
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php if($aspect_ratio):?><?php echo $_image_helper->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?php echo $_image_helper->init($_product, 'small_image')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="img-thumbnail" /></a>
                <div class="actions">
                	<ul class="list-actions">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:void(0)<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>onclick="ajaxWishlist(this,'<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');"<?php endif;?> class="addtowishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><i data-toggle="tooltip" data-placement="top" title="<?php echo $this->__('Add to Wishlist') ?>" class="icon icon-Heart"></i></a></li>
                            <?php endif; ?>
                            <?php if($product->isSaleable()): ?>
                                <?php  if ( !($product->getTypeInstance(true)->hasOptions($product) || $product->isGrouped()) ) :  ?>
                                    <li><a href="<?php if(!Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)): ?><?php echo $this->getAddToCartUrl($_product) ?><?php else: ?>javascript:void(0)<?php endif; ?>" class="addtocart" title="<?php echo $this->__('Add to Cart') ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>onclick="setLocationAjax(this,'<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId(); ?>')"<?php endif; ?>><i data-toggle="tooltip" data-placement="top" class="icon icon-ShoppingCart" title="<?php echo $this->__('Add to Cart') ?>"></i><!--<span>&nbsp;<?php //echo $this->__('Add to Cart') ?></span>--></a></li>
                                <?php else : ?>
                                    <li><a href="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>javascript:showOptions('<?php echo $_product->getId()?>')<?php else: ?><?php echo $this->getAddToCartUrl($_product) ?><?php endif; ?>" class="addtocart" title="<?php echo $this->__('Add to Cart') ?>"><i data-toggle="tooltip" data-placement="top" class="icon icon-ShoppingCart" title="<?php echo $this->__('Add to Cart') ?>"></i><?php /*?><span>&nbsp;<?php echo $this->__('Add to Cart') ?></span><?php */?></a>
                                    <a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Options</a></li>
                                <?php endif;?>
                            <?php else: ?>
                                <li><a href="javascript:void(0);" class="addtocart disabled outofstock" title="<?php echo $this->__('Out of stock') ?>"><i data-toggle="tooltip" data-placement="top" class="icon icon-ShoppingCart" title="<?php echo $this->__('Out of stock') ?>"></i></span></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:void(0)<?php else: ?><?php echo $_compareUrl ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>onclick="ajaxCompare(this,'<?php echo $_compareUrl ?>','<?php echo $_product->getId()?>');"<?php endif; ?> class="comparelink" title="<?php echo $this->__('Add to Compare') ?>"><i data-toggle="tooltip" data-placement="top" class="icon icon-Files" title="<?php echo $this->__('Add to Compare') ?>"></i></a></li>
                            <?php endif; ?></ul>
                </div>
                <?php //quick view
				if( Mage::getStoreConfig("quickview/general/enableview", $code) ){
                       $base_url = $this->getUrl();
                        if(strpos($base_url,'?')!==false)
                            $base_url = explode("?",$this->getUrl());
                        if(is_array($base_url))
                            $base_url = $base_url[0];
                        $base_url .= "quickview/index/view/";
                        $quickview_url = $base_url."id/".$_product->getId();
                        ?>
                        <a href="<?php echo $quickview_url; ?>" class="quickview-icon"><i class="icon icon-Eye"></i><?php /*?><span><?php echo $this->__("Quick View"); ?></span><?php */?></a>
                    <?php
                    }
                    ?>
            </div>
            <div class="product-details">
                <div class="product-info">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                    </h2>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </div>
            <?php /*?><?php if($_product->getRatingSummary()): ?>
            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
            <?php endif; ?><?php */?>
            <?php if($_themehelper->getConf("category_page/display_rating", $code)):?>
			<?php  if (Mage::helper('catalog')->isModuleEnabled('Mage_Review')):?>
					<?php
                        $review_html = $this->getReviewsSummaryHtml($product, 'short');
                        if($review_html){
                            echo $review_html;
                        }else{
						?>
                        <div class="ratings">
                            <div class="rating-box">
                                <div class="rating" style="width:0"></div>
						</div>
						</div>
					<?php
					}
					?>
			<?php endif; ?>
			<?php endif; ?>
           </div>
                    </div>
            <?php $total_items = ($this->getData('total_items'))?$this->getData('total_items'):'8' ?>
			<?php if (++$i == $total_items) break; ?>
                <?php endforeach; ?>
            </div> 
          </div>
          <script type="text/javascript">
			(function($){
			$(document).ready(function() {
				$("#tabbed_categories-<?php echo $catId; ?>").owlCarousel({
			items:<?php echo ($this->getData('item_count'))?$this->getData('item_count'):'3' ?>,
			<?php if($this->getData('rtl')==='true'):?>rtl:true,<?php endif;?>
			 margin:30,
			 responsive:{
				0:{
					items:1
				},
				480:{
					items:1
				},
				767:{
					items:2
				},
				991:{
					items:2
				},
				1024:{
					items:<?php echo ($this->getData('item_count'))?$this->getData('item_count'):'3' ?>
				}
			},
			nav: true,
			navText: ["<i class='icon-arrow-left icons'></i>","<i class='icon-arrow-right icons'></i>"],
			autoplay: true,
			autoplayTimeout: 5000,
			autoplayHoverPause: true,
			dots: false,
			nav: true,
			navRewind: true,
			loop: true,
		});
			});})(jQuery);
        	</script>
<?php endif; ?>