

<ul id="system_config_tabs" class="tabs config-tabs">

    <li>
        <dl>

            <dt class="label" style="">AlPesa Wallet</dt>

            <dd>
                <a href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/alpesa/users"); ?>"><span>Users</span></a>
            </dd>

            <dd>
                <a href=""><span>Wallet Analysis</span></a>
            </dd>

            <dd>
                <a href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/alpesa/payments"); ?>">
                    <span>Payments</span></a>
            </dd>

            <dd>
                <a href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/alpesa/configuration"); ?>">
                    <span>Configuration</span></a>
            </dd>

        </dl>
    </li>

</ul>
