<?php 
/**
 * Zozoconcepts_Brands extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Zozoconcepts
 * @package        Zozoconcepts_Brands
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Brand list template
 *
 * @category    Zozoconcepts
 * @package     Zozoconcepts_Brands
 * @author      Zozoconcepts Hybrid
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_brands = $this->getBrands(); ?>
<div class="page-title brand-title">
    <h1><?php echo Mage::helper('zozoconcepts_brands')->__('Brands') ?></h1>
</div>
<?php if ($_brands->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="brand-list-container">
    <?php foreach ($_brands as $_brand) : ?>
        <div class="brand-list-item">
            <a href="<?php echo $_brand->getBrandUrl()?>">
                <?php echo $_brand->getTitle();?>
            </a><br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('zozoconcepts_brands')->__('There are no brands at this moment');?>
<?php endif;?>
