<?php
/**
 * Zozoconcepts_Brands extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Zozoconcepts
 * @package        Zozoconcepts_Brands
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Brand view template
 *
 * @category    Zozoconcepts
 * @package     Zozoconcepts_Brands
 * @author      Zozoconcepts Hybrid
 */
?>
<?php $_brand = $this->getCurrentBrand();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title brand-title">
    <h1><?php echo $_brand->getTitle(); ?></h1>
</div>
<div class="brand-view">
    <div class="brand-brand_image">
        <?php if ($_brand->getBrandImage()) :?>
            <img src="<?php echo $this->helper('zozoconcepts_brands/brand_image')->init($_brand, 'brand_image');?>" alt="<?php echo $this->htmlEscape($_brand->getTitle());?>" />
        <?php endif;?>

    </div>
    <div class="brand-brand_descriptions">
        <?php echo $_brand->getBrandDescriptions();?>
    </div>
<?php echo $this->getChildHtml('brand_products')?>
</div>
