<?php

$trade_id = $_GET['trade_id'];
$trade = Mage::getModel('suppliertrading/trades')->load($trade_id);
$product  =  Mage::getModel('catalog/product')->load($trade->getProductId());

?>
<div class="container main-container vendor-container">
    <h1 class="text-center"><?php echo Mage::helper('suppliertrading')->__('Reject suggested price'); ?></h1>

    <div class="row">
        <div class="col-md-12 form-container">
            <form name="reject_suggest_price" id="reject_suggest_price"
                  action="<?php echo Mage::getUrl('suppliertrading/trade/rejectSave') ?>" method="post"
            >

                <div class="clearfix"></div>
                <div >
                    <div>
                        <div class="clearfix"></div>
                        <div class="col-md-6">
                            <strong>Product:</strong> <?php echo $product->getName(); ?>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-md-6">
                            <strong> Suggested price:</strong> <?php echo $trade->getPrice(); ?>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-md-6">
                            <strong> Quantity:</strong> <?php echo $trade->getQty(); ?>
                        </div> <br/><br/>
                        <div>
                            <input  type="hidden" name="trade_id"
                                   value="<?= $trade_id ?>"/>
                                <div class="col-md-6 label-container">
                                    <label for="note">
                                        <?php echo $this->__('Note for customer'); ?>
                                    </label>
                                </div>
                                <div class="col-md-6 input-container">
                                   <textarea name="note" id="note"></textarea>
                                </div>

                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-md-2 col-md-offset-5 col-sm-4 col-sm-offset-4">
                    <input type="submit" name="submit" class="btn btn-primary"
                           value="<?php echo $this->__('Save') ?>"/>
                </div>
            </form>
        </div>
    </div>
</div>