<?php
	$order_id=$this->getRequest()->getParam('order_id');
	if(!$order_id){
		$shipment = Mage::getModel('sales/order_shipment')->load($this->getRequest()->getParam('shipment_id'));
		$order_id=$shipment->getOrderId();
		
	}
	$CurrentUrl = Mage::helper('core/url')->getCurrentUrl();
	Mage::getSingleton('core/session')->setPreviousUrl($CurrentUrl); 
?>
<script type="text/javascript">
	//<![CDATA[		
	<?php 
	$data = array('order_id'=>$order_id);
	if($shipment_id = $this->getRequest()->getParam('shipment_id')){
		$data['shipment_id'] = $shipment_id;
	}
	
	$_url=Mage::helper("adminhtml")->getUrl('aramexshipment/shipment/printLabel/', $data);?>
	myObj.printLabelUrl='<?php echo $_url;?>';
   
	  //]]>
</script>