<?php
/**
 * Zozoconcepts_Blog extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Zozoconcepts
 * @package        Zozoconcepts_Blog
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Category view widget template
 *
 * @category    Zozoconcepts
 * @package     Zozoconcepts_Blog
 * @author      Zozoconcepts Hybrid
 */
?>
<?php $_category = $this->getCurrentCategory();?>
<?php if ($_category) :?>
    <div class="category-widget-view">
        <h3><?php echo $_category->getCatName()?></h3>
        <div>
            <div class="cat_name-widget">
                <?php echo Mage::helper('zozoconcepts_blog')->__('Name');?>:<?php echo $_category->getCatName();?>
            </div>
            <div class="cat_desc-widget">
                <?php echo Mage::helper('zozoconcepts_blog')->__('Category Description');?>:<?php echo $_category->getCatDesc();?>
            </div>

        </div>
    </div>
<?php endif;?>
