<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo $this->__('DIRECTPAYONLINE PAYMENT LOG') ?></h4>
    </div>
    <?php $paymentLogs = $this->getPaymentLogs();?>
    <fieldset>
        <?php if($paymentLogs->count() > 0):?>
        
        <div class="grid np">
            <table cellspacing="0" style="border:0;">
                <thead>
                    <tr class="headings">
                        <th>Order</th>
                        <th>Status</th>
                        <th>Date</th>
                    </tr> 
                </thead>
                <tbody>
                    <?php foreach ($paymentLogs as $paymentLog): ?>
                        <tr>
                            <td><?php echo $paymentLog->getOrderId();?></td>
                            <td><?php echo $paymentLog->getStatus();?></td>
                            <td><?php echo date('d-m-Y h:i:s',strtotime($paymentLog->getUpdatedAt()));?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        
        <?php else:?>
        <h4 style="color:#ff0000;">0 directpayonline logs for this order.</h4>
        <?php endif;?>
        
    </fieldset>
</div>
<div class="clear"></div>