
<style>
    .cust-direct-log:hover{
        cursor:pointer;
    }
    .order-direct-log-holder{
        height:500px;
        overflow-y:scroll;
    }
</style>
<?php $directCustomerLogs = $this->directCustomerLogs('admin'); ?>



    <div class="my-account">
        <div class="page-title title-buttons">
            <h1>DirectPayOnline Payment Logs</h1>
        </div>

        <?php if (count($directCustomerLogs) > 0): ?>
        <div class="col2-set">

            <div class="col-1">

                <h3>Complete Payments</h3>
                <div class="order-direct-log-holder">
                    <table class="data-table orders" id="my-orders-table">
                        <colgroup><col width="1">
                            <col width="1">
                            <col>
                            <col width="1">
                            <col width="1">
                            <col width="1">
                        </colgroup>
                        <thead>
                            <tr class="first last">
                                <th>Order</th>
                                <th>Status</th>
                                <th>Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($directCustomerLogs as $directCustomerLog):if ($directCustomerLog->getStatus() == 'complete'): ?>
                                    <tr class="first odd">
                                        <td><?php echo $directCustomerLog->getOrderId(); ?></td>
                                        <td><?php echo $directCustomerLog->getStatus(); ?></td>
                                        <td><?php echo date('d-m-Y h:i:s', strtotime($directCustomerLog->getUpdatedAt())); ?></td>
                                    </tr>
                                <?php
                                endif;
                            endforeach;
                            ?>
                        </tbody>
                    </table>
                </div>

            </div>

            <div class="col-2">

                <h3>Unverified Payments</h3>
                <div class="order-direct-log-holder">
                    <table class="data-table orders" id="my-orders-table">
                        <colgroup><col width="1">
                            <col width="1">
                            <col>
                            <col width="1">
                            <col width="1">
                            <col width="1">
                        </colgroup>
                        <thead>
                            <tr class="first last">
                                <th>Order</th>
                                <th>Status</th>
                                <th>Date</th>
                            </tr>
                        </thead>
                        <tbody>
    <?php foreach ($directCustomerLogs as $directCustomerLog):if ($directCustomerLog->getStatus() != 'complete'): ?>
                                    <tr class="first odd">
                                        <td><?php echo $directCustomerLog->getOrderId(); ?></td>
                                        <td><?php echo $directCustomerLog->getStatus(); ?></td>
                                        <td><?php echo date('d-m-Y h:i:s', strtotime($directCustomerLog->getUpdatedAt())); ?></td>
                                    </tr>
                                <?php
                                endif;
                            endforeach;
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

        
<?php else: ?>
    <h3>0 Payment Logs</h3>
<?php endif; ?>
    </div>


