<?php if ($this->getReviewsCount()): ?>
    <div class="ratings">
        <?php if ($this->getRatingSummary()):?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif;?>
        <p class="rating-links">
        <?php if($this->getReviewsCount() > '1'):?>
        <a href="<?php echo $this->getReviewsUrl() ?>"><?php echo $this->__('%s Reviews', $this->getReviewsCount()) ?></a>
		<?php else:?>
		<a href="<?php echo $this->getReviewsUrl() ?>"><?php echo $this->__('%s Review', $this->getReviewsCount()) ?></a> 		
		<?php endif;?>
            <span class="separator">|</span>
            <a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Add Your Review') ?></a>
        </p>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>
