<?php
    $contacts_config = $this->helper('Zozothemes\Varmo\Helper\Data')->getConfig('varmo_settings/contacts');
    $_infoblock = $contacts_config['infoblock'];
?>
<div class="row">
    <div class="col-sm-8"><?php echo $this->getChildHtml('contactForm')?></div>
    <div class="col-sm-4 contact-info">
        <div class="section-title"><h3 class="title"><?php echo __('Contact Details') ?></h3></div>
        <?php echo $_infoblock; ?>
    </div>
</div>
<?php echo $this->getChildHtml('google_map')?>