<?php $_items = $this->getFlatCollection(); ?>

<?php $isDiscountEff = Mage::getStoreConfig( 'marketplace_configuration/general/is_discount_effective' ); ?>
<?php $statusToSee = Mage::helper( 'marketplace' )->getStatusesCanSee(); ?>
<div class="container main-container vendor-container">
    <h1 class="text-center"><?php echo $this->__( 'Orders' ) ?></h1>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <form name="report_filter" id="report_filter"
                  action="<?php echo Mage::getUrl( '*/*/*' ) ?>" method="post"
                  enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-2">
                        <input type="text" class="form-control input-text"
                               placeholder="Autoincrement ID"
                               name="autoincrement_id"
                               value="<?php echo $this->escapeHtml( $this->getRequest()->getPost( 'autoincrement_id',
                                   '' ) ); ?>"/>
                    </div>
                    <div class="col-md-2">
                        <input type="text"
                               class="form-control datepicker input-text input-text validate-date"
                               name="from"
                               value="<?php echo $this->escapeHtml( $this->getRequest()->getPost( 'from',
                                   '' ) ); ?>"
                               placeholder=<?php echo $this->__( 'From' ) ?>/>
                    </div>
                    <div class="col-md-2">
                        <input type="text"
                               class="form-control datepicker input-text input-text validate-date"
                               name="to"
                               value="<?php echo $this->escapeHtml( $this->getRequest()->getPost( 'to',
                                   '' ) ); ?>"
                               placeholder=<?php echo $this->__( 'To' ) ?>/>
                    </div>
                    <div class="col-md-2">
                        <select name="status" placeholder="From">
                            <option value=""> Status</option>
                            <?php foreach ( Mage::getModel( 'sales/order_status' )->getResourceCollection() AS $status ): ?>
                                <?php if ( in_array( $status->getStatus(),
                                    $statusToSee ) ): ?>
                                    <option
                                        value="<?php echo $status->getStatus() ?>"<?php echo $status->getStatus() == $this->getRequest()->getPost( 'status',
                                        '' ) ? ' selected="selected"' : ""; ?>><?php echo $status->getLabel() ?></option>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="col-md-1">
                        <input type="submit" name="submit"
                               class="btn btn-primary btn-sm"
                               value="<?php echo $this->__( 'Filter' ) ?>"/>
                    </div>
                    <div class="col-md-2">
                        <button
                            class="btn btn-sm export-to-csv"><?php echo $this->__( 'Export to CSV' ) ?></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class='table-responsive'>
                <table class="table table-striped">
                    <thead>
                    <th><?php echo $this->__( 'Order #' ) ?></th>
                    <th><?php echo $this->__( 'Purchased On' ) ?></th>
                    <th><?php echo $this->__( 'Bill to Name' ) ?></th>
                    <th><?php echo $this->__( 'Ship to Name' ) ?></th>
                    <th><?php echo $this->__( 'Subtotal' ) ?></th>
                    <th><?php echo $this->__( 'Income' ) ?></th>
                    <?php if ( $isDiscountEff ): ?>
                        <th><?php echo $this->__( 'Discount' ) ?></th>
                        <th><?php echo $this->__( 'With Discount' ) ?></th>
                    <?php endif; ?>
                    <th><?php echo $this->__( 'Status' ) ?></th>
                    <th><?php echo $this->__( 'Actions' ) ?></th>
                    </thead>
                    <tbody>
                    <?php if ( $_items->count() ): ?>
                        <?php foreach ( $_items AS $item ): ?>
                                <?php $subtotal = $this->calculateSubtotal( $item ); ?>
                                <?php if ( $isDiscountEff ): ?>
                                    <?php $discount = $this->calculateDiscount( $item ); ?>
                                <?php endif; ?>
                                <tr class="item">
                                    <td>
                                        #<?php echo $item->getIncrementId(); ?></td>
                                    <td><?php echo Mage::helper('core')->formatDate(
                                            $item->getCreatedAt(),
                                            Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM,
                                            true
                                        ); ?>
                                    </td>
                                    <td><?php echo $this->escapeHtml( $item->getBillingAddress()->getName() ); ?></td>
                                    <td><?php if ( $item->getShippingAddress() ): ?><?php echo $this->escapeHtml( $item->getShippingAddress()->getName() ); ?><?php endif; ?></td>
                                    <td><?php echo Mage::helper('core' )->currency( $subtotal ); ?></td>
                                    <td>
                                        <?php echo Mage::helper('core')
                                            ->currency(
                                                Mage::helper('marketplace/order')->calculateIncome($item)
                                            );
                                        ?>
                                    </td>
                                    <?php if ( $isDiscountEff ): ?>
                                        <td><?php echo Mage::helper( 'core' )->currency( $discount ); ?></td>
                                        <td>
                                            <?php echo Mage::helper('core')
                                                ->currency(
                                                    Mage::helper('marketplace/order')->calculateIncome($item) - $discount
                                                );
                                            ?>
                                        </td>
                                    <?php endif; ?>
                                    <td><?php echo ucfirst( $item->getStatus() ); ?></td>
                                    <td>
                                        <a href="<?php echo Mage::getUrl( 'marketplace/order/view/',
                                            array( 'id' => $item->getId() ) ) ?>"
                                           class="btn btn-primary"><?php echo $this->__( 'View' ); ?></a>
                                        <?php if ( $this->canShowShipButton( $item ) ): ?>
                                            <a href="<?php echo Mage::getUrl( 'marketplace/shipment/create/',
                                                array( 'id' => $item->getId() ) ) ?>"
                                               class="btn btn-primary btn-success"><?php echo $this->__( 'Ship' ); ?></a>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <td colspan="7"><?php echo $this->__( "No results" ); ?></td>
                    <?php endif; ?>
                    </tbody>
                    <tfoot>
                    <th><?php echo $this->__( 'Order #' ) ?></th>
                    <th><?php echo $this->__( 'Purchased On' ) ?></th>
                    <th><?php echo $this->__( 'Bill to Name' ) ?></th>
                    <th><?php echo $this->__( 'Ship to Name' ) ?></th>
                    <th><?php echo $this->__( 'Subtotal' ) ?></th>
                    <th><?php echo $this->__( 'Income' ) ?></th>
                    <?php if ( $isDiscountEff ): ?>
                        <th><?php echo $this->__( 'Discount' ) ?></th>
                        <th><?php echo $this->__( 'With Discount' ) ?></th>
                    <?php endif; ?>
                    <th><?php echo $this->__( 'Status' ) ?></th>
                    <th><?php echo $this->__( 'Actions' ) ?></th>
                    </tfoot>
                </table>
                <?php echo $this->getPagerHtml(); ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    //< ![CDATA[
    var customForm = new VarienForm('report_filter');
    //]]>
    jQuery(document).ready(function ($) {
        jQuery('.datepicker').datepicker();

        jQuery('#report_filter input[type="submit"]').click(function (e) {
            var actionExport = '<?php echo $this->getUrl( '*/*/*' ) ?>';
            var form = jQuery('#report_filter');
            form.attr('action', actionExport);
            form.submit();
        });

        jQuery('.export-to-csv').click(function (e) {
            var actionExport = '<?php echo $this->getUrl( '*/*/exportCsv' ) ?>';
            var form = jQuery('#report_filter');
            form.attr('action', actionExport);
            form.submit();
        });
    });
</script>
