<?php $_order = $this->getOrder(); ?>
<?php
$orderStoreDate = $this->formatDate($_order->getCreatedAtStoreDate(), 'medium', true);
?>
<div class="container vendor-container">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h2 class="text-center">
                    <?php echo $this->__('Order #%s', $_order->getIncrementId()); ?>
                </h2>
                <div class="row">
                    <div class="col-md-5">
                        <h3 class='margin-bottom-mobile'>
                            <?php echo $this->__("Order Information"); ?>
                        </h3>
                        <p><strong><?php echo $this->__("Order Date"); ?>
                                : </strong> <?php echo $orderStoreDate; ?></p>
                        <p>
                            <strong><?php echo $this->__("Order Status"); ?>
                                : </strong>

                            <?php if ($_order->getStatus() == 'canceled') : ?>
                                <span
                                        class="text-danger"><?php echo ucfirst($_order->getStatus()); ?></span>
                            <?php else : ?>
                                <?php if ($this->canChangeOrderStatus()) : ?>
                                    <?php echo $this->getStatusSelectHtml(); ?>
                                <?php else : ?>
                                    <?php echo ucfirst($_order->getStatus()); ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        </p>
                    </div>
                    <div class="col-md-5">
                        <h3 class='margin-bottom-mobile'><?php echo $this->__("Account Information"); ?></h3>
                        <p><strong><?php echo $this->__("Customer Name"); ?>
                                : </strong> <?php echo $this->escapeHtml($_order->getCustomerFirstname()); ?> <?php echo $this->escapeHtml($_order->getCustomerLastname()); ?>
                        </p>
                        <p><strong><?php echo $this->__("Email"); ?>
                                : </strong> <a
                                    href="mailto:<?php echo $_order->getCustomerEmail(); ?>">
                                <?php echo $this->escapeHtml($_order->getCustomerEmail()); ?>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div role="tabpanel">
        <ul class="nav nav-tabs" role="tablist" style='margin-left: 0'>
            <li<?php echo $this->getCurrentTab() == 'products' ? " class=\"active\"" : "" ?>>
                <a href="#order" role="tab"
                   data-toggle="tab"><?php echo $this->__('Information'); ?></a>
            </li>
            <?php if (!$_order->getIsVirtual()) : ?>
                <li<?php echo $this->getCurrentTab() == 'shipment' ? " class=\"active\"" : "" ?>>
                    <a href="#shipments" role="tab"
                       data-toggle="tab"><?php echo $this->__('Shipments'); ?></a>
                </li>
            <?php endif; ?>
            <li<?php echo $this->getCurrentTab() == 'invoice' ? " class=\"active\"" : "" ?>>
                <a href="#invoices" role="tab"
                   data-toggle="tab"><?php echo $this->__('Invoices'); ?></a>
            </li>
        </ul>
        <div class="tab-content">
            <div
                    class="tab-pane<?php echo $this->getCurrentTab() == 'products' ? " active" : "" ?>"
                    id="order">
                <?php echo $this->getChild('view_order')
                    ->setOrder($_order)
                    ->setItems($this->getItems())
                    ->toHtml(); ?>
            </div>
            <?php if (!$_order->getIsVirtual()) : ?>
                <div
                        class="tab-pane<?php echo $this->getCurrentTab() == 'shipment' ? " active" : "" ?>"
                        id="shipments">
                    <?php echo $this->getChild('view_shipments')->setOrder($_order)->toHtml(); ?>
                </div>
            <?php endif; ?>
            <div
                    class="tab-pane<?php echo $this->getCurrentTab() == 'invoice' ? " active" : "" ?>"
                    id="invoices"><?php echo $this->getChild('view_invoices')->setOrder($_order)->toHtml(); ?></div>
        </div>
    </div>
</div>

<script>
    jQuery(document).ready(function () {
        jQuery("#status_id").change(function () {
            var alertResponse = confirm(
                "<?php echo $this->__("Do you want change this order status?"); ?>"
            );

            if (!alertResponse) {
                return false;
            }

            window.location = "<?php echo $this->getChangeStatusUrl(); ?>status/" + jQuery(this).val();
        });
    });
</script>