/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'varmo-icons\'">' + entity + '</span>' + html;
	}
	var icons = {
		'varmo-icon-user-female': '&#xe000;',
		'varmo-icon-people': '&#xe001;',
		'varmo-icon-user-l': '&#xe005;',
		'varmo-icon-trophy': '&#xe006;',
		'varmo-icon-speedometer': '&#xe007;',
		'varmo-icon-social-youtube': '&#xe008;',
		'varmo-icon-social-twitter': '&#xe009;',
		'varmo-icon-social-tumblr': '&#xe00a;',
		'varmo-icon-social-facebook': '&#xe00b;',
		'varmo-icon-social-dropbox': '&#xe00c;',
		'varmo-icon-social-dribbble': '&#xe00d;',
		'varmo-icon-shield': '&#xe00e;',
		'varmo-icon-magnet': '&#xe016;',
		'varmo-icon-game-controller': '&#xe01b;',
		'varmo-icon-handbag': '&#xe035;',
		'varmo-icon-basket-loaded': '&#xe04d;',
		'varmo-icon-basket-l': '&#xe04e;',
		'varmo-icon-bag': '&#xe04f;',
		'varmo-icon-trash': '&#xe054;',
		'varmo-icon-tag': '&#xe055;',
		'varmo-icon-camera': '&#xe07f;',
		'varmo-icon-clock-l': '&#xe081;',
		'varmo-icon-eye': '&#xe087;',
		'varmo-icon-lock': '&#xe08e;',
		'varmo-icon-paypal': '&#xe608;',
		'varmo-icon-social-instagram': '&#xe609;',
		'varmo-icon-social-linkedin': '&#xe60a;',
		'varmo-icon-social-pintarest': '&#xe60b;',
		'varmo-icon-social-github': '&#xe60c;',
		'varmo-icon-social-google': '&#xe60d;',
		'varmo-icon-social-reddit': '&#xe60e;',
		'varmo-icon-social-skype': '&#xe60f;',
		'varmo-icon-social-behance': '&#xe610;',
		'varmo-icon-social-foursqare': '&#xe611;',
		'varmo-icon-social-soundcloud': '&#xe612;',
		'varmo-icon-social-spotify': '&#xe613;',
		'varmo-icon-social-stumbleupon': '&#xe614;',
		'varmo-icon-worldglobal': '&#xe601;',
		'varmo-icon-panties': '&#xe602;',
		'varmo-icon-tees': '&#xe603;',
		'varmo-icon-shorts': '&#xe604;',
		'varmo-icon-tie': '&#xe605;',
		'varmo-icon-shoe': '&#xe615;',
		'varmo-icon-scisor': '&#xe618;',
		'varmo-icon-play': '&#xe616;',
		'varmo-icon-pause': '&#xe617;',
		'varmo-icon-rugby-ball': '&#xe623;',
		'varmo-icon-zandu-balm': '&#xe62d;',
		'varmo-icon-up-direction': '&#xe62e;',
		'varmo-icon-tele': '&#xe636;',
		'varmo-icon-choco-bar': '&#xe646;',
		'varmo-icon-sand-watch': '&#xe648;',
		'varmo-icon-fork': '&#xe64d;',
		'varmo-icon-juicer': '&#xe650;',
		'varmo-icon-desktop': '&#xe655;',
		'varmo-icon-srew': '&#xe656;',
		'varmo-icon-alarm': '&#xe668;',
		'varmo-icon-timer': '&#xe669;',
		'varmo-icon-basket': '&#xe720;',
		'varmo-icon-line-plane': '&#xe671;',
		'varmo-icon-phone-l': '&#xe674;',
		'varmo-icon-micro-phone': '&#xe67a;',
		'varmo-icon-home': '&#xe67d;',
		'varmo-icon-heart': '&#xe722;',
		'varmo-icon-handset': '&#xe67f;',
		'varmo-icon-chart-bar': '&#xe753;',
		'varmo-icon-expand': '&#xe687;',
		'varmo-icon-trash-can': '&#xe689;',
		'varmo-icon-mini-truck': '&#xe694;',
		'varmo-icon-layout': '&#xe697;',
		'varmo-icon-watch': '&#xe698;',
		'varmo-icon-users': '&#xe69b;',
		'varmo-icon-user-male': '&#xe69c;',
		'varmo-icon-tagged': '&#xe6a0;',
		'varmo-icon-search': '&#xe723;',
		'varmo-icon-bell': '&#xe6a7;',
		'varmo-icon-pointer': '&#xe6ab;',
		'varmo-icon-un-lock': '&#xe6ad;',
		'varmo-icon-mike': '&#xe6b1;',
		'varmo-icon-mail-box': '&#xe6b7;',
		'varmo-icon-big-eye': '&#xe6bc;',
		'varmo-icon-locked': '&#xe6c2;',
		'varmo-icon-up-open': '&#xe700;',
		'varmo-icon-right-open': '&#xe701;',
		'varmo-icon-left-open': '&#xe702;',
		'varmo-icon-down-open': '&#xe703;',
		'varmo-icon-small-up-open': '&#xe704;',
		'varmo-icon-small-right-open': '&#xe705;',
		'varmo-icon-small-left-open': '&#xe706;',
		'varmo-icon-small-down-open': '&#xe707;',
		'varmo-icon-thin-up-open': '&#xe708;',
		'varmo-icon-thin-right-open': '&#xe709;',
		'varmo-icon-thin-left-open': '&#xe710;',
		'varmo-icon-thin-down-open': '&#xe711;',
		'varmo-icon-huge-up-open': '&#xe712;',
		'varmo-icon-huge-right-open': '&#xe713;',
		'varmo-icon-huge-left-open': '&#xe714;',
		'varmo-icon-huge-down-open': '&#xe715;',
		'varmo-icon-angle-up': '&#xe716;',
		'varmo-icon-angle-right': '&#xe717;',
		'varmo-icon-angle-left': '&#xe718;',
		'varmo-icon-angle-down': '&#xe719;',
		'varmo-icon-cancel': '&#xe724;',
		'varmo-icon-cancel-mini': '&#xe725;',
		'varmo-icon-up-dir': '&#xe726;',
		'varmo-icon-right-dir': '&#xe727;',
		'varmo-icon-left-dir': '&#xe728;',
		'varmo-icon-down-dir': '&#xe729;',
		'varmo-icon-phone': '&#xe730;',
		'varmo-icon-pencil': '&#xe731;',
		'varmo-icon-pencil-mini': '&#xe732;',
		'varmo-icon-menu': '&#xe733;',
		'varmo-icon-location': '&#xe734;',
		'varmo-icon-mail': '&#xe735;',
		'varmo-icon-ok': '&#xe737;',
		'varmo-icon-plus-squared-alt': '&#xe738;',
		'varmo-icon-minus-squared-alt': '&#xe739;',
		'varmo-icon-plus-squared': '&#xe740;',
		'varmo-icon-minus-squared': '&#xe741;',
		'varmo-icon-facebook': '&#xe745;',
		'varmo-icon-twitter': '&#xe746;',
		'varmo-icon-linkedin': '&#xe747;',
		'varmo-icon-pinterest': '&#xe748;',
		'varmo-icon-google': '&#xe749;',
		'varmo-icon-youtube': '&#xe750;',
		'varmo-icon-heart-empty': '&#xe754;',
		'varmo-icon-up': '&#xe755;',
		'varmo-icon-right': '&#xe756;',
		'varmo-icon-down': '&#xe757;',
		'varmo-icon-left': '&#xe758;',
		'varmo-icon-star': '&#xe759;',
		'varmo-icon-star-empty': '&#xe760;',
		'varmo-icon-ok-circled': '&#xe761;',
		'varmo-icon-cancel-circled': '&#xe762;',
		'varmo-icon-help-circled': '&#xe763;',
		'varmo-icon-info-circled': '&#xe764;',
		'varmo-icon-attention': '&#xe765;',
		'varmo-icon-mail-alt': '&#xe767;',
		'varmo-icon-skype': '&#xe768;',
		'varmo-icon-user': '&#xe770;',
		'varmo-icon-help': '&#xe771;',
		'varmo-icon-info': '&#xe772;',
		'varmo-icon-help-circled-alt': '&#xe773;',
		'varmo-icon-info-circled-alt': '&#xe774;',
		'varmo-icon-chevron-left': '&#xe775;',
		'varmo-icon-chevron-right': '&#xe776;',
		'varmo-icon-reply': '&#xe777;',
		'varmo-icon-paper-plane': '&#xe778;',
		'varmo-icon-tumblr': '&#xe918;',
		'varmo-icon-vimeo': '&#xe91a;',
		'varmo-icon-chat': '&#xf860;',
		'varmo-icon-minus': '&#xe900;',
		'varmo-icon-plus': '&#xe901;',
		'varmo-icon-clock': '&#xe736;',
		'varmo-icon-truck': '&#xe742;',
		'varmo-icon-dollar': '&#xe743;',
		'varmo-icon-th': '&#xe751;',
		'varmo-icon-th-list': '&#xe752;',
		'varmo-icon-mobile': '&#xe766;',
		'varmo-icon-doc': '&#xe769;',
		'varmo-icon-magnify': '&#xe779;',
		'varmo-icon-zoom-in': '&#xe780;',
		'varmo-icon-zoom-out': '&#xe781;',
		'varmo-icon-checkmark': '&#xe782;',
		'varmo-icon-bomb': '&#xe783;',
		'varmo-icon-printer': '&#xe784;',
		'varmo-icon-lifebuoy': '&#xe744;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/varmo-icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
