<?php
/**
 * Zozoconcepts_Socio extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Zozoconcepts
 * @package        Zozoconcepts_Socio
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Twitter block
 *
 * @category    Zozoconcepts
 * @package     Zozoconcepts_Socio
 * @author      Zozoconcepts Hybrid
 */
?>
<?php 
$themehelper = Mage::helper('hybrid');
$helper = Mage::helper('zozoconcepts_socio'); ?>
<?php //if($helper->isEnabled()): ?>
	<?php if($helper->enableSocial()):?><li class="header-social"><ul class="social-icons social-icons-transparent">
			<?php if($helper->facebook()):?><li><a href="<?php echo $helper->facebook()?>" target="new"><i class="fa fa-facebook"></i></a></li><?php endif; ?>
			<?php if($helper->googleplus()):?><li><a href="<?php echo $helper->googleplus()?>" target="new"><i class="fa fa-google-plus"></i></a></li><?php endif; ?>
			<?php if($helper->twitter()):?><li><a href="<?php echo $helper->twitter()?>" target="new"><i class="fa fa-twitter"></i></a></li><?php endif; ?>
			<?php if($helper->youtube()):?><li><a href="<?php echo $helper->youtube()?>" target="new"><i class="fa fa-youtube"></i></a></li><?php endif; ?>
			<?php if($helper->dribbble()):?><li><a href="<?php echo $helper->dribbble()?>" target="new"><i class="fa fa-dribbble"></i></a></li><?php endif; ?></ul></li>
	<?php endif; ?>
<?php //endif; ?>
