<?php 
/**
 * Zozoconcepts_Blog extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Zozoconcepts
 * @package        Zozoconcepts_Blog
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Category list template
 *
 * @category    Zozoconcepts
 * @package     Zozoconcepts_Blog
 * @author      Zozoconcepts Hybrid
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_categories = $this->getCategories(); ?>
<div class="page-title category-title">
    <?php if(Mage::helper('zozoconcepts_blog/category')->isRssEnabled()) : ?>
        <a href="<?php echo Mage::helper('zozoconcepts_blog/category')->getRssUrl();?>" class="link-rss"><?php echo Mage::helper('zozoconcepts_blog')->__('Subscribe to RSS Feed')?></a>
    <?php endif;?>
    <h1><?php echo Mage::helper('zozoconcepts_blog')->__('Categories') ?></h1>
</div>
<?php if ($_categories->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="category-list-container">
    <?php foreach ($_categories as $_category) : ?>
        <div class="category-list-item">
            <a href="<?php echo $_category->getCategoryUrl()?>">
                <?php echo $_category->getCatName();?>
            </a><br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
   	<div class="clearfix"></div>
    <p class="notice notice-msg"><?php echo Mage::helper('zozoconcepts_blog')->__('There are no categories at this moment');?></p>
<?php endif;?>
