<?php 
/**
 * Zozoconcepts_Blog extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Zozoconcepts
 * @package        Zozoconcepts_Blog
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Category list template
 *
 * @category    Zozoconcepts
 * @package     Zozoconcepts_Blog
 * @author      Zozoconcepts Hybrid
 */
?>
<?php $_categories = $this->getCategories(); ?>
<div class="block block-blog">
    <div class="block-title">
        <strong><span><?php echo Mage::helper('zozoconcepts_blog')->__('Categories') ?></span></strong>
    </div>
    <div class="block-content">
    <?php if ($_categories->getSize() > 0) :?>
        <ul class="category-list-container">
        <?php foreach ($_categories as $_category) : ?>
            <li class="category-list-item">
                <a href="<?php echo $_category->getCategoryUrl()?>"><?php echo $_category->getCatName();?></a>
            </li>
        <?php endforeach;?>
        </ul>
    <?php else : ?>
        <?php echo Mage::helper('zozoconcepts_blog')->__('There are no categories at this moment');?>
    <?php endif;?>
    </div>
</div>
  
  
  
  