<?php
/**
 * @category  Apptrian
 * @package   Apptrian_FacebookPixel
 * @author    Apptrian
 * @copyright Copyright (c) 2017 Apptrian (http://www.apptrian.com)
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License
 */
?>
<?php
/**
 * Facebook Pixel Code block
 *
 * @var $block Apptrian_FacebookPixel_Block_Code
 */

$data   = $this->getFacebookPixelData();
$id     = $data['id'];
$action = $data['full_action_name'];

?>
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');

fbq('init', '<?php echo $this->escapeHtml($id) ?>');
fbq('track', 'PageView');

<?php if ($action == 'cms_index_index'): ?>
fbq('track', 'ViewContent');
<?php elseif ($action == 'cms_page_view'): ?>
fbq('track', 'ViewContent');
<?php elseif ($action == 'catalog_category_view'
    || $action == 'catalog_category_default'
    || $action == 'catalog_category_layered'): ?>
fbq('track', 'ViewContent');
<?php elseif ($action == 'catalog_product_view'): ?>

<?php
$productData = $this->getProductData();
if ($productData !== null): ?>
fbq('track', 'ViewContent', {
    content_name: '<?php echo $this
        ->escapeHtml($productData['content_name']) ?>',
    content_ids: ['<?php echo $this
        ->escapeHtml($productData['content_ids']) ?>'],
    content_type: 'product',
    value: <?php echo $this->escapeHtml($productData['value']) ?>,
    currency: '<?php echo $this->escapeHtml($productData['currency']) ?>'
});
//Add Pixel Events to the button's click handler
if (typeof jQuery != 'undefined') {
    jQuery('.add-to-cart .btn-cart').click(function() {
        fbq('track', 'AddToCart', {
            content_name: '<?php echo $this
                ->escapeHtml($productData['content_name']) ?>',
            content_ids: ['<?php echo $this
                ->escapeHtml($productData['content_ids']) ?>'],
            content_type: 'product',
            value: <?php echo $this->escapeHtml($productData['value']) ?>,
            currency: '<?php echo $this->escapeHtml($productData['currency'])?>'
        });
    });
}
<?php endif; ?>

<?php elseif ($action == 'catalogsearch_result_index'
    || $action == 'catalogsearch_advanced_result'): ?>
fbq('track', 'Search');
<?php elseif ($action == 'customer_account_create'): ?>
fbq('track', 'CompleteRegistration');
<?php elseif ($action == 'checkout_onepage_index'
    || $action == 'onepagecheckout_index_index'
    || $action == 'onestepcheckout_index_index'
    || $action == 'opc_index_index'): ?>
fbq('track', 'InitiateCheckout');
<?php elseif ($action == 'checkout_onepage_success'
    || $action == 'onepagecheckout_index_success'): ?>

<?php
$orderData = $this->getOrderData();
if ($orderData !== null):?>
fbq('track', 'Purchase', {
<?php if (array_key_exists('content_name', $orderData)): ?>
    content_name: '<?php echo $this->escapeHtml($orderData['content_name']) ?>',
<?php endif; ?>
    content_ids: [<?php echo $this->escapeHtml($orderData['content_ids']) ?>],
    content_type: 'product',
    value: <?php echo $this->escapeHtml($orderData['value']) ?>,
    currency: '<?php echo $this->escapeHtml($orderData['currency']) ?>'
});
<?php endif; ?>

<?php elseif ($action == 'wishlist_index_index'): ?>
fbq('track', 'AddToWishlist');
<?php else: ?>
fbq('track', 'ViewContent');
<?php endif; ?>

</script>
<noscript><img height="1" width="1" style="display:none" alt="Facebook Pixel" 
src="https://www.facebook.com/tr?id=<?php echo $this
    ->escapeHtml($id) ?>&ev=PageView&noscript=1"/></noscript>
<!-- End Facebook Pixel Code -->
