<?php
/*
 * @var Cminds_SupplierRedirection_Block_Domain $this
 * */
?>
<div class="container-fluid main-container vendor-container">
    <div class="container form-container">
        <h1 class="text-left">
            <?php echo Mage::helper( 'supplierfrontendproductuploader' )
                ->__( 'Domain Url Settings' ); ?>
        </h1>
        <form name="settings_supplier_profile" id="settings_supplier_profile"
              action="<?php echo $this->getFormActionUrl() ?>" method="post"
              enctype="multipart/form-data">
            <div class="row">
                <div class="col-sm-6">

                    <div class="form-group">
                        <label for="domain" class="required control-label">
                            <?php echo $this->__( 'Domain' ); ?> <em>*</em>
                        </label>
                        <div class="input-container">
                            <input type="text" id="domain" name="domain"
                                   class="input-text required-entry form-control validate-length maximum-length-60"
                                   value="<?php echo $this->getDomain(); ?>"/>
                            <p class="help-block">
                                <?php echo $this->helper("marketplace")->__("This domain will be used on profile page and for product links."); ?>
                                <br>
                                <?php echo $this->helper("marketplace")->__("Provided link should be placed without following http:// and ending /"); ?>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-2">
                    <input type="submit" name="clear" class="btn btn-primary"
                           value="<?php echo $this->__( 'Save' ) ?>"/>
                </div>
        </form>
    </div>
</div>