<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <button type="button" title="<?php echo $buttonTitle ?>" class="btn btn-grey addtocart" onclick="productAddToCartForm.submit(this)"><?php echo $buttonTitle ?></button>
        <span id='ajax_loader' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>
		<?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>