<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>
<?php if(Mage::getStoreConfig('ajaxcart/addtolinks/enableproduct')): ?>
	<ul class="add-to-links actions">
	<?php if ($this->helper('wishlist')->isAllow()) : ?>
		<li><a href="#" onclick="ajaxWishlist(this,'<?php echo $_wishlistSubmitUrl ?>','<?php echo $_product->getId()?>'); return false;" class="btn btn-grey link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><i class="icon icon-Heart"></i></a></li>
	<?php endif; ?>
	<?php
		$_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
	?>
	<?php if($_compareUrl) : ?>
		<li><span class="separator">|</span> <a href="#" onclick="ajaxCompare(this,'<?php echo $_compareUrl?>','<?php echo $_product->getId()?>'); return false;" class="btn btn-grey link-compare" title="<?php echo $this->__('Add to Compare') ?>"><i class="icon icon-Files"></i></a></li>
	<?php endif; ?>    
	</ul>
<?php else : ?>
	<ul class="add-to-links actions">
	<?php if ($this->helper('wishlist')->isAllow()) : ?>
		<li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="btn btn-grey link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><i class="icon icon-Heart"></i></a></li>
	<?php endif; ?>
	<?php
		$_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
	?>
	<?php if($_compareUrl) : ?>
		<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="btn btn-grey link-compare" title="<?php echo $this->__('Add to Compare') ?>"><i class="icon icon-Files"></i></a></li>
	<?php endif; ?>
	</ul>
<?php endif;?>	